# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mstar specific clk
#

obj-y += clk-msc313e_cpuclk.o \
	 clk-msc313e_clkgen-pll.o \
	 clk-msc313e_clkgen-mux.o \
	 clk-mstar-upll.o \
	 clk-mstar_lpll.o \
	 clk-mstar_clkgen-gates.o \
	 clk-mstar_miupll.o \
	 clk-mstar-mpll.o \
	 clk-mstar-pll_common.o
